souk/core/urls.py
try:
    from django.conf.urls import *
except ImportError:  # django < 1.4
    from django.conf.urls.defaults import *

# place app url patterns here

souk/urls.py
from django.conf.urls import patterns, include, url
from django.core.urlresolvers import reverse_lazy

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'souk.core.views.home', name='home'),
    url(r'^me/$', 'souk.core.views.me', name='me'),
    url(r'^balance/$', 'souk.core.views.balance', name='balance'),
    url(r'^address/$', 'souk.core.views.address', name='address'),
    url(r'^nest$', 'souk.core.views.nest', name='nest'),
    url(r'^items/new$', 'souk.core.views.new_item', name='new_item'),
    url(r'^request/(?P<item_id>\d+)/$', 'souk.core.views.request_item', name='request_item'),
    url(r'^request/(?P<item_id>\d+)/confirm/$', 'souk.core.views.request_item_confirm', name='request_item_confirm'),

    url(r'^borrowed/$', 'souk.core.views.borrowed', name='borrowed'),
    url(r'^return/(?P<item_id>\d+)/$', 'souk.core.views.return_item', name='return_item'),

    url(r'^requests/$', 'souk.core.views.list_requests', name='list_requests'),
    url(r'^requests/(?P<req_id>\d+)/accept/$', 'souk.core.views.accept_request', name='accept_request'),

    url(r'^backlog$', 'souk.core.views.backlog', name='backlog'),

    # url(r'^souk/', include('souk.foo.urls')),


    url(r'^search/$', 'souk.core.views.search', name='search'),
    url(r'^craigslist/$', 'souk.core.views.craigslist', name='craigslist'),
    url(r'^craigslist/submit/$', 'souk.core.views.cragslist_submit', name='cragslist_submit'),
    url(r'^craigslist/submit/(?P<req_id>\d+)/$', 'souk.core.views.craigslist_reply', name='craigslist_reply'),

    url(r'^accept/(?P<req_id>\d+)/(?P<hash>\w+)/$', 'souk.core.views.craigslist_accept', name='craigslist_reply'),
    url(r'^accept/(?P<req_id>\d+)/(?P<hash>\w+)/done$', 'souk.core.views.craigslist_accept_done', name='craigslist_reply'),

    url(r'^login/$', 'django.contrib.auth.views.login',name="login"),
    url(r'^logout/$', 'django.contrib.auth.views.logout', {"next_page" : reverse_lazy('login')}, name="logout"),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url('', include('social.apps.django_app.urls', namespace='social'))
)

souk/core/models.py
import os
import uuid

from django.db import models
from django.conf import settings


def get_file_path(instance, filename):
    ext = filename.split('.')[-1]
    filename = "%s.%s" % (uuid.uuid4(), ext)
    return os.path.join('item_imgs', filename)


class Item(models.Model):
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='+')
    possessor = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='+')

    name = models.CharField(blank=False, max_length=250)
    desc = models.TextField(blank=True)
    picture = models.ImageField(blank=True, upload_to=get_file_path)

    class Meta:
        verbose_name = "Item"
        verbose_name_plural = "Items"

    def filename(self):
        return os.path.basename(self.picture.name)

    def __str__(self):
        return unicode(self.name)


class Nest(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    code = models.CharField(blank=False, max_length=250)
    access_token = models.TextField(blank=False)
    updated = models.DateTimeField(auto_now=True)
    home = models.CharField(blank=True, max_length=15)

    class Meta:
        verbose_name = "Nest"
        verbose_name_plural = "Nests"

    def __str__(self):
        return unicode(self.user)


class Request(models.Model):
    requestor = models.ForeignKey(settings.AUTH_USER_MODEL)
    item = models.ForeignKey(Item, related_name='requests', blank=True, null=True)
    craig = models.ForeignKey("CraigPost", blank=True, null=True)
    address = models.CharField(blank=True, max_length=450)
    added = models.DateTimeField(auto_now_add=True)

    accepted = models.BooleanField(default=False)
    in_progress = models.BooleanField(default=False)
    completed = models.BooleanField(default=False)

    cost_delivery = models.IntegerField(default=0)
    delivery_id = models.CharField(blank=True, max_length=50)
    delivery_estimate = models.DateTimeField(blank=True, null=True)
    pickup_estimate = models.DateTimeField(blank=True, null=True)

    class Meta:
        verbose_name = "Request"
        verbose_name_plural = "Requests"

    def __str__(self):
        return unicode(self.item) + unicode(self.requestor)


class Profile(models.Model):
    address = models.TextField(blank=False)
    phone_number = models.CharField(blank=False, max_length=50)

    user = models.ForeignKey(settings.AUTH_USER_MODEL, blank=True, related_name='profile')
    balance = models.DecimalField(default=0, max_digits=5, decimal_places=2)

    class Meta:
        verbose_name = "Profile"
        verbose_name_plural = "Profiles"

    def __str__(self):
        return unicode(self.address)


class CraigPost(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    url = models.URLField()
    title = models.CharField(blank=False, max_length=250)
    email = models.EmailField()
    added = models.DateTimeField(auto_now_add=True)

    price = models.IntegerField(default=0)
    address = models.CharField(blank=True, max_length=450)
    completed = models.BooleanField(default=True)

    class Meta:
        verbose_name = "CraigPost"
        verbose_name_plural = "CraigPosts"

    def __str__(self):
        return unicode(self.title)


class Message(models.Model):
    post = models.ForeignKey(CraigPost, blank=True, null=True)
    text = models.TextField()
    added = models.DateTimeField(auto_now_add=True)
    from_us = models.BooleanField(default=True)

    class Meta:
        verbose_name = "Message"
        verbose_name_plural = "Messages"

    def __str__(self):
        return unicode(self.text)

souk/core/forms.py
from django import forms

from .models import Item

class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ['name', 'desc', 'picture']

souk/core/views.py
import json
import requests
import mandrill
import hashlib

from django.core.mail import send_mail
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.db.models import F, Q
from django.core.cache import cache
from django.http import HttpResponse
from django.views.decorators.csrf import csrf_exempt

from social.apps.django_app.default.models import UserSocialAuth

from .models import Item, Nest, Request, CraigPost, Message, Profile
from .forms import ItemForm
from .scrape import scrape_craigslist

# from .delivery import postmate, Location, DeliveryQuote
from . import delivery

def update_nest_status(user):
    nest = Nest.objects.filter(user=user).first()
    if nest is None:
        return False, 'home'

    response = requests.get('https://developer-api.nest.com/structures?auth={0}'.format(nest.access_token))
    data = response.json()
    nest.home = data[data.keys()[0]]['away']
    nest.save()
    return True, nest.home


@csrf_exempt
def home(request):
    if request.user.is_authenticated():
        return redirect('/search')

    if 'mandrill_events' in request.POST:

        msg = json.loads(request.POST.get('mandrill_events'))[0]

        msg_text = msg['msg']['text']
        from_email = msg['msg']['from_email']

        post = CraigPost.objects.filter(email=from_email).all()[0]

        the_msg = Message(text=msg_text, from_us=False)
        the_msg.post = post
        the_msg.save()

    return render(request, 'home.html', None)


@login_required
def me(request):
    data = {
        'items': Item.objects.filter(owner=request.user).order_by('possessor'),
        'success': 'success' in request.GET,
    }

    profile = Profile.objects.filter(user=request.user).first()
    if profile is None:
        return redirect("/address")

    if 'topup' in request.GET:
        profile.balance += int(request.GET.get('topup'))
        profile.save()

    # social = request.user.social_auth.get(provider='facebook')
    # response = requests.get(
    #     'https://graph.facebook.com/me',
    #     params={'access_token': social.extra_data['access_token']}
    # )
    # print response.json()

    print

    return render(request, 'me.html', data)


@login_required
def new_item(request):
    i = ItemForm(request.POST, request.FILES)
    if i.is_valid():
        new_item = i.save(commit=False)
        new_item.owner = new_item.possessor = request.user
        new_item.save()
        return redirect('/me?success')
    return redirect('/me?fail')


@login_required
def nest(request):
    print request.GET

    if request.GET.get('state') == "STATE" and 'code' in request.GET:
        nest, created = Nest.objects.get_or_create(user=request.user)
        nest.code = request.GET.get('code')

        response = requests.post('https://api.home.nest.com/oauth2/access_token?client_id=6ccafabb-4945-4590-9fa9-b8f7e2b5d613&code={0}&client_secret=5bHqEETnOkuNIsFKLSe5oDwe3&grant_type=authorization_code'.format(nest.code))

        data = response.json()
        nest.access_token = data['access_token']
        nest.save()

        return redirect('/')
    else:
        return redirect('https://home.nest.com/login/oauth2?client_id=6ccafabb-4945-4590-9fa9-b8f7e2b5d613&state=STATE')


@login_required
def search(request):
    data = {
        'requested': request.GET.get('requested'),
    }

    friend_uids = cache.get('friend_uids_{0}'.format(request.user.id))
    if not friend_uids:
        social = request.user.social_auth.filter(provider='facebook').first()
        response = requests.get(
            'https://graph.facebook.com/{0}/friends'.format(social.uid),
            params={'access_token': social.extra_data['access_token'], 'fields': 'id,name,picture', 'limit': '5000'}
            )

        friends = response.json()
        friend_uids = map(lambda x: int(x['id']), friends['data'])
        cache.set('friend_uids_{0}'.format(request.user.id), friend_uids, 60*60)


    data['friend_social'] = UserSocialAuth.objects.filter(uid__in=friend_uids).select_related('user')
    data['friends'] = map(lambda x: x.user, data['friend_social'])

    data['items'] = Item.objects.filter(owner__in=data['friends'], owner=F('possessor'))

    return render(request, 'search.html', data)


@login_required
def request_item(request, item_id):
    item = get_object_or_404(Item, id=item_id)

    data = {
        'item': item
    }

    quote = delivery.api.post_delivery_quote(item.owner.profile.get().address, request.user.profile.get().address)
    print quote
    data['delivery_quote'] = quote['fee'] / 100
    data['quote'] = quote

    return render(request, 'request.html', data)


@login_required
def request_item_confirm(request, item_id):
    item = get_object_or_404(Item, id=item_id)

    data = {
        'item': item
    }

    req = Request(requestor=request.user, item=item)
    req.save()

    message = '''
Hello!

You have a new request for "{0}"! Please approve it at http://reciproxity.me/requests

Thanks!
Reciproxity
'''.format(item.name)


    send_mail("New Reciproxity Request", message,
    "{0} {1} <hello@reciproxity.me>".format(request.user.first_name, request.user.last_name), [item.owner.email])

    return redirect('/search?requested=' + item_id)

@login_required
def address(request):
    data = {}
    if 'address' in request.POST and 'phone_number' in request.POST:
        profile, created = Profile.objects.get_or_create(user=request.user)
        profile.address = request.POST.get('address')
        profile.phone_number = request.POST.get('phone_number')
        profile.save()
        return redirect('/me')

    return render(request, 'address.html', data)

@login_required
def borrowed(request):
    data = {}

    data['borrowed'] = Item.objects.filter(~Q(owner=F('possessor')), possessor=request.user)
    data['requests'] = Request.objects.filter(requestor=request.user, completed=False)

    data['owed'] = sum(map(lambda x: x.requests.order_by('-id').first().cost_delivery, data['borrowed'])) / 100.

    data['owed_full'] = data['owed'] * 100

    return render(request, 'borrowed.html', data)

@login_required
def return_item(request, item_id):
    item = get_object_or_404(Item, id=item_id)

    req = Request(requestor=item.owner, accepted=True, item=item)
    req.save()

    return redirect("/requests")

@login_required
def list_requests(request):
    data = {'accepted': 'accepted' in request.GET}

    data['requests'] = Request.objects.filter(item__possessor=request.user, completed=False).order_by('accepted')
    data['outstanding'] = Item.objects.filter(~Q(owner=F('possessor')), owner=request.user) #Request.objects.filter(item__owner=request.user, completed=True)



    return render(request, 'requests.html', data)


@login_required
def accept_request(request, req_id):
    req = get_object_or_404(Request, id=req_id, item__owner=request.user)
    req.accepted = True
    req.save()
    return redirect('/requests?accepted')


def backlog(request):
    pending_requests = Request.objects.filter(accepted=True, in_progress=False, completed=False)

    data = {
        'pending_requests': str(pending_requests)
    }

    all_users = set()
    for req in pending_requests:
        all_users.add(req.requestor)
        if req.item:
            all_users.add(req.item.possessor)
    data['users'] = map(str, all_users)
    all_user_presence = dict()

    for user in all_users:
        connected_account, status = update_nest_status(user)
        all_user_presence[user] = status
    data['all_user_presence'] = str(all_user_presence)

    for req in pending_requests:
        if (not req.item and all_user_presence[req.requestor] == 'home') or all_user_presence[req.requestor] == all_user_presence[req.item.possessor] == 'home':
            pickup = None
            if req.item:
                pickup = delivery.Location('{0} {1}'.format(req.item.possessor.first_name, req.item.possessor.last_name),
                                     req.item.possessor.profile.get().address,
                                     req.item.possessor.profile.get().phone_number)
            else:
                pickup = delivery.Location('Craigslist User',
                                     req.address,
                                     '1 212 555 5555')
            dropoff = delivery.Location('{0} {1}'.format(req.requestor.first_name, req.requestor.last_name),
                                 req.requestor.profile.get().address,
                                 req.requestor.profile.get().phone_number)

            if req.item:
                manifest = '{0}'.format(req.item.name)
            else:
                manifest = 'verify item - ' + req.craig.title
            de = delivery.Delivery(delivery.api, manifest, pickup, dropoff)
            de.create()
            print de
            req.pickup_estimate = de.pickup_eta
            req.delivery_estimate = de.dropoff_eta
            req.delivery_id = de.delivery_id
            req.in_progress = True
            req.cost_delivery = de.fee
            req.save()

    in_progress = Request.objects.filter(accepted=True, in_progress=True, completed=False)
    data['in_progress'] = map(str, in_progress)
    for req in in_progress:
        print req
        del_data = delivery.api.get_delivery_data(req.delivery_id)
        req.pickup_estimate = del_data.get('pickup_eta')
        req.delivery_estimate = del_data.get('dropoff_eta')
        if del_data.get('status') == 'delivered':
            req.completed = True
            from decimal import Decimal
            paid = False
            if req.item:
                before_p = req.item.possessor
                req.item.possessor = req.requestor
                if req.item.possessor == req.item.owner:
                    profile = Profile.objects.filter(user=before_p).first()
                    profile.balance -= Decimal(req.cost_delivery) / Decimal(100)

souk/templates/accept.html
{% extends "base.html" %}

{% block content %}

<div data-alert class="alert-box secondary" style="margin:0">
<h2>Accepting Offer for "{{post.title}}"</h2>
</div>
<br>

<div class="row">
Agreed-upon account of <b>${{post.price}}</b>

<form action="/accept/{{post.id}}/{{hash}}/done" method="post"><br>
{% csrf_token %}
<b>Address:</b> <textarea name="address"></textarea>
<p>Your address will not be availalbe to the reciproxity user to protect your privacy</p>

<h4>Payment Method</h4>
<p>We have escrowed the requested funds from the buyer and will hold them until Postmates has confirmed delivery. At that time, we will disburse payment to your preferred payment solution:</p>

<input type="radio" name="payment" value="Red" id="paymentRed"><label for="paymentRed">PayPal</label>
<input type="radio" name="payment" value="Blue" id="paymentBlue"><label for="paymentBlue">Stripe</label>
<input type="radio" name="payment" value="Green" id="paymentGreen"><label for="paymentGreen">Bitcoin</label><br>

<button type="submit">Submit &amp; Accept</button>
</form>

</div>

{% endblock content %}

souk/templates/accept_done.html
{% extends "base.html" %}

{% block content %}
<div data-alert class="alert-box secondary" style="margin:0">
<h2>Offer accepted!</h2>
<p>A Postmate messenger will be visiting you shortly to pick up the item</p>

</div>
<br>
{% endblock content %}

souk/templates/address.html
{% extends "base.html" %}

{% block content %}
<div data-alert class="alert-box secondary" style="margin:0">
    <p>In order to know where to send your items, please enter your address and phone number</p>
</div>
<br>

<div class="row">
    <form method="post" action="/address/">
    {% csrf_token %}
        <p>
            <b>Address:</b>
            <textarea name="address"></textarea>
        </p>

        <p><b>Phone Number</b>: <input type="text" name="phone_number" placeholder="ex 212 555 5555"></p>

        <button type="submit">Continue</button>
    </form>
</div>

<div data-alert class="alert-box secondary" style="margin:0">
    <h1>Nest</h1>

    <a href="/nest" target="_blank">Connect your Nest</a>
</div>
{% endblock content %}

souk/templates/balance.html
{% extends "base.html" %}

{% block content %}
<div data-alert class="alert-box success" style="margin:0">
<h2>Balance: ${{user.profile.first.balance}}</h2>

Top up your balance with <input id="balance_add">

<p>
<form action="/payment/new" method="POST">
<!-- We're using the latest v3 API here -->
<script
src="https://checkout.stripe.com/v3/checkout.js" class="stripe-button"
data-key="pk_test_Nei7IV3TO9Go2ValDrQtXyjW"
data-amount="{{owed_full}}"
data-name="Payment Charges"
data-description="Delivery Fee"
data-currency="usd"
data-image="/static/img/placeholder.png">
</script>
</form>

<a href='#' class="button tiny secondary" id="topup">Top-up</a>
</p>
</div>
{% endblock content %}

{% block js %}
<script>
$("#topup").click(function(event){
    event.preventDefault();
    // $('.stripe-button').data('amount') = $('#balance_add').val() * 100;
    window.location = '/me?topup=' + $('#balance_add').val()
})
</script>
{% endblock js %}

souk/templates/base.html
{% load compress %}
<!doctype html>
<html class="no-js" lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Reciproxity &mdash; {% block title %}Home{% endblock title %}</title>
    <link rel="stylesheet" href="/static/css/foundation.css" />
    <script src="/static/js/vendor/modernizr.js"></script>
    {% block css %}{% endblock css %}
</head>
<body>

    <nav class="top-bar" data-topbar role="navigation">
        <ul class="title-area">
            <li class="name">
                <h1><a href="/">Reciproxity</a></h1>
            </li>
            <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
            <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
        </ul>
        <section class="top-bar-section">
            <!-- Right Nav Section -->
            <ul class="right">
                {% if user.is_authenticated %}
                <li><a href="/balance">Balance: ${{user.profile.first.balance}}</a></li>
                {% if user.profile.first.balance < 10 %}
                    <li><a href="/balance">Recharge Balance</a></li>
                {% endif %}
                <li class="has-dropdown">
                    <a href="#">Hello {{user.first_name}}</a>
                    <ul class="dropdown">
                        <li><a href="mailto:admin@pavawith.me">Contact us</a></li>
                        <li><a href="/logout">Logout</a></li>
                    </ul>
                </li>
                {% else %}
                <li><a href="/login">Login</a></li>
                {% endif %}
            </ul>
            <!-- Left Nav Section -->
            {% if user.is_authenticated %}<ul class="left">
                <li><a href="/search">Search</a></li>
                <li><a href="/craigslist">Craigslist</a></li>
                <li><a href="/me">My Items</a></li>
                <li><a href="/requests">Requests</a></li>
                <li><a href="/borrowed">Borrowed Items</a></li>
            </ul>{% endif %}
        </section>
    </nav>

    {% block content %}{% endblock content %}

    <footer class="row">
        <div class="large-12 columns">
            <hr/>
            <div class="row">
                <div class="large-8 columns">
                    <p>&copy; Copyright 2014 <a href="http://rohunbansal.com/">Rohun Bansal</a>, Joe Farned, Michael Gromis.</p>
                </div>
                <!--<div class="large-4 columns">
                    <ul class="inline-list right">
                        <li><a href="/privacy">Privacy Policy</a></li>
                        <li><a href="/terms">Terms of Use</a></li>
                    </ul>
                </div>-->
            </div>
        </div>
    </footer>

    {% compress js %}
    <script src="/static/js/vendor/jquery.js"></script>
    <script src="/static/js/foundation.min.js"></script>
    {% endcompress %}
    <script>
        $(document).foundation();
    </script>

    {% block js %}{% endblock js %}
</body>
</html>

souk/templates/craigslist.html
{% extends "base.html" %}

{% block content %}

<div data-alert class="alert-box secondary"style="margin:0">
	<h3 class="text-center">Enter Craigslist URL</h3>

	<form action="/craigslist/submit/" method="post">
	{% csrf_token %}
	<input type="text" placeholder="Enter Craigslist URL" name="url">

	<textarea rows="4" cols="50" name="email_body">Email Body</textarea>

	<button type="submit">Submit</button>
	</form>
</div>

<div data-alert class="alert-box primary" style="margin:0">
<h2>Active Responses</h2>
</div>
<br>

<center><a href="#" id="show-completed">Toggle Showing Completed</a></center>

{% for post in posts %}
<div class="row item{% if post.request_set.count %} completed" style="background: #AFA{% endif %}">
    {% if post.request_set.first %}
        <div data-alert class="alert-box success" style="margin:0">
        Request Completed!
        </div>
    {% endif %}

    <div class="large-12 columns">
        <h4>{{post.title}}</h4>
        <p><a href="{{post.url}}" target="_blank">{{post.url}}</a></p>

        {% for msg in post.message_set.all %}
            {% if msg.from_us %}
                <b>From You:</b><br>
                {% else %}
                <b>From Them:</b><br>
            {% endif %}
            {{msg}}
            <hr>
        {% endfor %}

        <form action="/craigslist/submit/{{post.id}}/" method="post">
        {% csrf_token %}
        <textarea rows="4" cols="50" name="email_body">Email Body</textarea>

        <input id="send_link" name="send_link" type="checkbox"><label for="send_link">Send confirmation link to Craigslist Poster (will be withdrawn from your balance)</label>

        <div class="row collapse prefix-radius">
                <div class="small-1 columns">
                  <span class="prefix">$</span>
                </div>
                <div class="small-11 columns">
                  <input type="text" placeholder="Agreed-upon price" name="price">
                </div>
              </div>
        <button type="submit">Submit</button>
        </form>
    </div>
</div>
{% endfor %}

{% endblock content %}

{% block js %}
<script>
$('.completed').hide()
$('#show-completed').click(function(event){
    event.preventDefault();
    $('.completed').toggle()
})
</script>
{% endblock js %}

souk/templates/home.html
{% extends "base.html" %}

{% block content %}
<div class="row">
<img src="/static/img/front.png">
</div>
<div data-alert class="alert-box secondary row">
    <a href="{% url 'social:begin' 'facebook' %}?next={{ request.path }}" class="button" style="width:100%">Login with Facebook</a>
</div>

<div class="row">
<p>Reciproxity drives efficient exchanges on Craigslist by employing Postmates to deliver items between buyers and sellers. To order an item, users only need to paste the craigslist url into the interface, which instantly links the buyer and seller through email, using Mandrill.</p>

<p>Separately, Reciproxity lets users create a lending library of goods for friends to borrow from. When an item is requested, Postmates synchronizes the delivery. When Nest determines both users are home, Reciproxity initiates delivery. Users login with Facebook and track their friends’ lending libraries.</p>
</div>
{% endblock content %}

souk/templates/me.html
{% extends "base.html" %}

{% block content %}
{% if success %}
<div data-alert class="alert-box success" style="margin:0">
  Item added
  <a href="#" class="close">&times;</a>
</div>
{% endif %}

<div data-alert class="alert-box secondary" style="margin:0">
<h2>My Items</h2>
</div>

<div data-alert class="alert-box secondary">
    <h3 class="text-center">Add a item</h3>
    <hr>

    <form action="/items/new" method="post" id="new-account" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="row">
            <div class="large-4 columns">
                <label>Item Name
                    <input type="text" placeholder="Item Name" name="name" id="name">
                </label>
            </div>
            <div class="large-5 columns">
                <label>Item Description
                    <textarea type="text" placeholder="Item Description" name="desc" id="desc"></textarea>
                </label>
            </div>
            <div class="large-3 columns">
                <label>Item Picture
                    <input type="file" placeholder="Item Picture" name="picture" id="id_picture">
                </label>
            </div>
        </div>
        <div class="row">
            <div class="large-8 columns">
                Your items will only be shared with your facebook friends. You will be asked before items are queued for delivery.
            </div>
            <div class="large-4 columns clearfix">
                <input type="submit" href="#" class="button radius right" value="Add Item">
            </div>
        </div>
    </form>
</div>




{% for item in items %}
<div class="row item">
    <div class="small-12 large-3 columns text-center" style="padding-bottom: 15px">
        {% if item.picture %}<img src="/media/{{item.filename}}">{% else %}<img src="/static/img/placeholder.png" style="height: 200px">{% endif %}
    </div>
    <div class="small-4 large-5 columns">
        <h4>{{item.name}}</h4>
        <p>{{item.desc}}</p>
    </div>
    <div class="small-6 large-4 columns">
        <p><b>Owner:</b> {{item.owner.first_name}} {{item.owner.last_name}}</p>
        <p><b>Possessor:</b> {{item.possessor.first_name}} {{item.possessor.last_name}} {% if item.possessor == user %} (You){% endif %}</p>
        <hr>
        <h5>Options</h5>
        <p>
            <a href='#' class="button tiny expand">Delete</a>
            <a href="https://www.facebook.com/sharer/sharer.php?u=http://reciproxity.me" target="_blank">Share on Facebook</a> or <a href="https://twitter.com/home?status=http://reciproxity.me" target="_blank">Share on Twitter</a>
        </p>
    </div>
</div>
<hr>
{% endfor %}
{% endblock content %}